### PR TITLE
Maven migration

### PR DESCRIPTION
**Pull request by pfichtner**
Migrated from ant (build.xml) to maveb (pom.xml)
This is now a maven multi-module project
Using args4j for now for argument parsing
JARs now are runnable JARs (purged sh/bat scripts)

### CODE REVIEW

**Comment by pfichtner** [comment]
any issus with this patch? Waiting for acceptance because of a dependent patch to push

**Comment by LucianoZu** [comment]
Hi Peter,
I was in holidays. Give me just a couple of days and I'll look at your
maven scripts. Thank you I was thinking about maven but there's so many
work to do! But what about you? I'm so happy you appreciate my library.
Where do you live? How are you using Ardulink? What about your work?

Luciano
Il 30/ago/2015 23:20, "Peter Fichtner" notifications@github.com ha
scritto:

**Comment by LucianoZu** [comment]
Ok,
I'm looking at your code.

Could explain to me why have you upgraded java version 5 to 6? I know 5 is very old but in this way Ardulink is compatble with a lot of code

**Comment by pfichtner** [comment]
Oh well! Nice! I thought of something is making trouble so sorry for the impatience! 
No: No reason for increasing the Java version: Please turn it back to Java 5

**Comment by LucianoZu** [comment]
ok,

I've merged your enhancement. Java is 1.6. There is some issues about assemble and example runs we have to work on.

**Pull request merged**
